spring.application.name=receitas-despensa-backend

# Conexão com o Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/receitas_de_despensa
spring.datasource.username=root
spring.datasource.password=2004

# Configurações do JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Chave secreta para assinar os tokens JWT.
jwt.secret=CHAVE_SECRETA_SUPER_LONGA_E_DIFICIL_DE_ADIVINHAR

# Credenciais da API Edamam
edamam.api.app-id=ef09f57c
edamam.api.app-key=fd94de282baf897ffb7d200e4a1b9eb1
